### ISSUE TITLE
Issue with ie7

### ISSUE THREAD

**Issue by alexvicegrab** [nicoles/elusive-icons-sass-rails#2]
Hello,

I've installed your Gem (via a Gemfile). I have all dependencies satisfied:

```
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
```

However, the second import does not work:

```
@import 'elusive-webfont';
@import 'elusive-webfont-ie7';
```

And if I do the first import, all works well, but the 2nd one breaks the rake precompilation (see error below)

Additionally, if I only include the 1st one, I get a weird error where the icons appear as empty squares and the code inspector complains it can't find the tiff/svg/woff files.
In my local server @ localhost:3000 everything looks fine.

My live site, in case it is useful is @ www.tangotranslation.com. I'd appreciate some advice here. Thank you :)

---

```
RAILS_ENV=production rake assets:precompile --trace
```

```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
Sass::SyntaxError: File to import not found or unreadable: elusive-webfont-ie7.
Load paths:
  /Users/sasha/Sites/tangoLyricsDB/app/assets/images
  /Users/sasha/Sites/tangoLyricsDB/app/assets/javascripts
  /Users/sasha/Sites/tangoLyricsDB/app/assets/stylesheets
  /Users/sasha/Sites/tangoLyricsDB/vendor/assets/javascripts
  /Users/sasha/Sites/tangoLyricsDB/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/chartkick-1.2.4/app/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/elusive-icons-sass-rails-1.0.0.0/vendor/assets/fonts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/elusive-icons-sass-rails-1.0.0.0/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/fonts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/turbolinks-2.2.2/lib/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/jquery-rails-3.1.0/vendor/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/coffee-rails-4.0.1/lib/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets
  (in /Users/sasha/Sites/tangoLyricsDB/app/assets/stylesheets/bootstrap_config.css.scss:3)
/Users/sasha/Sites/tangoLyricsDB/app/assets/stylesheets/bootstrap_config.css.scss:3
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:67:in `rescue in import'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:45:in `import'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:28:in `imported_file'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:37:in `css_import?'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-rails-4.0.3/lib/sass/rails/template.rb:22:in `evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:44:in `block in init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:37:in `map'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:37:in `init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/asset.rb:24:in `from_hash'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:37:in `init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/asset.rb:24:in `from_hash'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sasha/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/rake:23:in `load'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/rake:23:in `<main>'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Sass::SyntaxError: File to import not found or unreadable: elusive-webfont-ie7.
Load paths:
  /Users/sasha/Sites/tangoLyricsDB/app/assets/images
  /Users/sasha/Sites/tangoLyricsDB/app/assets/javascripts
  /Users/sasha/Sites/tangoLyricsDB/app/assets/stylesheets
  /Users/sasha/Sites/tangoLyricsDB/vendor/assets/javascripts
  /Users/sasha/Sites/tangoLyricsDB/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/chartkick-1.2.4/app/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/elusive-icons-sass-rails-1.0.0.0/vendor/assets/fonts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/elusive-icons-sass-rails-1.0.0.0/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/fonts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/turbolinks-2.2.2/lib/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/jquery-rails-3.1.0/vendor/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/coffee-rails-4.0.1/lib/assets/javascripts
  /Users/sasha/.rvm/gems/ruby-2.1.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:65:in `import'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:28:in `imported_file'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/import_node.rb:37:in `css_import?'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sass-rails-4.0.3/lib/sass/rails/template.rb:22:in `evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:44:in `block in init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:37:in `map'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:37:in `init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/asset.rb:24:in `from_hash'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:37:in `init_with'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/asset.rb:24:in `from_hash'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sasha/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/sasha/.rvm/gems/ruby-2.1.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/rake:23:in `load'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/rake:23:in `<main>'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/sasha/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by alexvicegrab** [comment]
Part of the question is solved here (icons now work)
http://stackoverflow.com/questions/16669991/most-of-my-assets-suddenly-return-404-after-a-push-to-heroku

```
# Do not fallback to assets pipeline if a precompiled asset is missed.
config.assets.compile = true
```

But this is a very suboptimal solution, as it makes the app slow.
But ie7 icons are still not precompling

**Comment by alexvicegrab** [comment]
Old issue, irrelevant since IE 7 is deprecated.
